version: "3"
services:

  kafka:
    image: 'bitnami/kafka:3.5.1'
    container_name: kafka01
    volumes:
      - "kafka_data:/bitnami"
    ports:
      - "9092:9092"
    networks:
      - local
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=INTERNAL://:9091,EXTERNAL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka01:9091,EXTERNAL://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka01:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka01:9091 --list" ]
      interval: 5s
      timeout: 10s
      retries: 5

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: kafka_ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka01:9091
      - KAFKA_CLUSTERS_0_NAME=kraft
    networks:
      - local
#
#  init-kafka:
#    image: confluentinc/cp-kafka:6.1.1
#    container_name: kafka_init
#    depends_on:
#      - kafka
#    entrypoint: [ '/bin/sh', '-c' ]
#    networks:
#      - local
#    command: |
#      "
#      # blocks until kafka is reachable
#      kafka-topics --bootstrap-server kafka01:9091 --list
#      echo -e 'Creating kafka topics'
#      kafka-topics --bootstrap-server kafka01:9091 --create --if-not-exists --topic one.topic --replication-factor 1 --partitions 1
#
#      echo -e 'Successfully created the following topics:'
#      kafka-topics --bootstrap-server kafka01:9091 --list
#      "


volumes:
  kafka_data:
    driver: local

networks:
  local: